### ISSUE TITLE
Peer Review - Max Weygandt

### ISSUE THREAD

**Issue by MWeygandt** [AntonKireyev/WebTechProject#5]
Wow, your website is fantastic!!!

Technical:
1. Clicking on pins on the map is inaccurate unless zoomed very far in. The pins that are behind another one are very difficult to click on,
2. There was no way to access a contact page.

Suggestions:
1. I really like the infographics page. Maybe if you could add more specific Boston facts that would be cool too.
2. If possible, add something where people can review restaurants that were selected for them. You could even add a leaderboard with the highest-star restaurant from their reviews. This might be too difficult to implement but it would be cool.

Awesome job.

**Comment by AntonKireyev** [comment]
Hi Max,
Thanks for your comments!
I'll make sure to check the map and perhaps find a different way to implement it. I'll also make sure to create a contact page.

I'll see what I can do about adding more specific boston facts.
I might be able to add some sort of form that then displays user reviews on the website, thanks for the idea!
